In [1]:
import pandas as pd
from pathlib import Path

In [12]:
df=pd.read_csv('data\daily_sales_data_0.csv')
df

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\Acer\AppData\Local\Temp\ipykernel_32548\4022079874.py:1: SyntaxWarning: invalid escape sequence '\d'
  df=pd.read_csv('data\daily_sales_data_0.csv')

                product  price  quantity        date region
0           pink morsel  $3.00       546  2018-02-06  north
1           pink morsel  $3.00       549  2018-02-06  south
2           pink morsel  $3.00       577  2018-02-06   east
3           pink morsel  $3.00       519  2018-02-06   west
4           gold morsel  $9.99       580  2018-02-06  north
...                 ...    ...       ...         ...    ...
13715  vermilion morsel  $4.99       504  2019-06-10   west
13716      lapis morsel  $1.99       521  2019-06-10  north
13717      lapis morsel  $1.99       502  2019-06-10  south
13718      lapis morsel  $1.99       536  2019-06-10   east
13719      lapis morsel  $1.99       515  2019-06-10   west

[13720 rows x 5 columns]

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13720 entries, 0 to 13719
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   product   13720 non-null  str
 1   price     13720 non-null  str
 2   quantity  13720 non-null  int64
 3   date      13720 non-null  str
 4   region    13720 non-null  str
dtypes: int64(1), str(4)
memory usage: 536.1 KB

In [7]:
df.head

<bound method NDFrame.head of                 product  price  quantity        date region
0           pink morsel  $3.00       546  2018-02-06  north
1           pink morsel  $3.00       549  2018-02-06  south
2           pink morsel  $3.00       577  2018-02-06   east
3           pink morsel  $3.00       519  2018-02-06   west
4           gold morsel  $9.99       580  2018-02-06  north
...                 ...    ...       ...         ...    ...
13715  vermilion morsel  $4.99       504  2019-06-10   west
13716      lapis morsel  $1.99       521  2019-06-10  north
13717      lapis morsel  $1.99       502  2019-06-10  south
13718      lapis morsel  $1.99       536  2019-06-10   east
13719      lapis morsel  $1.99       515  2019-06-10   west

[13720 rows x 5 columns]>

In [ ]:
data_folder = Path("data")


csv_files = list(data_folder.glob("*.csv"))


dfs = []

for file in csv_files:
    df = pd.read_csv(file)

   
    df = df[df["product"] == "pink morsel"]

    
    df["price"] = (
        df["price"]
        .astype(str)
        .str.replace("$", "", regex=False)
        .astype(float)
    )
        
    df["Sales"] = df["quantity"] * df["price"]

    
    df = df[["Sales", "date", "region"]]

   
    df.columns = ["Sales", "Date", "Region"]

    dfs.append(df)

final_df = pd.concat(dfs, ignore_index=True)


final_df.to_csv("formatted_output.csv", index=False)

print("Output file created: formatted_output.csv")
print(final_df.head())

Output file created: formatted_output.csv
    Sales        Date Region
0  1638.0  2018-02-06  north
1  1647.0  2018-02-06  south
2  1731.0  2018-02-06   east
3  1557.0  2018-02-06   west
4  1587.0  2018-02-07  north

In [11]:
df=pd.read_csv('formatted_output.csv')
df

       Sales        Date Region
0     1638.0  2018-02-06  north
1     1647.0  2018-02-06  south
2     1731.0  2018-02-06   east
3     1557.0  2018-02-06   west
4     1587.0  2018-02-07  north
...      ...         ...    ...
5875  2390.0  2022-02-13   west
5876  2035.0  2022-02-14  north
5877  2465.0  2022-02-14  south
5878  2500.0  2022-02-14   east
5879  2115.0  2022-02-14   west

[5880 rows x 3 columns]